on:  
  push:
    branches:
      - main

name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    environment: Main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: corretto
    - uses: subosito/flutter-action@v2
      with:
        channel: master
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test
    - name: Release to github pages
      uses: erickzanardo/flutter-gh-pages@v7
      with:
        baseHref: /abctechapp/
    - run: flutter build apk --debug
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}
        tag: v0.1.${{ github.run_number }}
        commit: main
